[all_follow]
nixpkgs = "nixpkgs"

[inputs]
[inputs.nixpkgs]
url = "github:NixOS/nixpkgs/nixpkgs-unstable"

[inputs.hjem]
url = "github:feel-co/hjem"

[inputs.nix-darwin]
url = "github:nix-darwin/nix-darwin"

[inputs.claude]
url = "github:sadjow/claude-code-nix"
