[all_follow]
nixpkgs = "nixpkgs"

[inputs]
[inputs.nixpkgs]
url = "github:NixOS/nixpkgs/nixpkgs-unstable"

[inputs.hjem]
url = "github:feel-co/hjem"
exclude_follow = ["nixpkgs"] # packages.<system>.hjem is cached

[inputs.ncro]
url = "github:manic-systems/ncro"
exclude_follow = ["nixpkgs"]      # packages.<system>.ncro is cached

[inputs.nix-darwin]
url = "github:nix-darwin/nix-darwin"

[inputs.claude]
url = "github:sadjow/claude-code-nix"
